# site
title: "Passeport culturel à Montpellier"

encoding: utf-8
safe: false
future: true

## permalinks
permalink: /blog/:year/:month/:day/:title/
relative_permalinks: false

## urls
url: https://benknoble.github.io/passeport-culturel
baseurl: ""
urlimg: https://benknoble.github.io/passeport-culturel/images/

## pagination
paginate: 5
paginate_path: "/blog/page:num"

## backgrounds
default_bg: sitebg.jpg
default_logo: sitelogo.png

## about/contact
author:
  name: Ben Knoble
  url: https://www.gitshowcase.com/benknoble
  avatar: benknoble.png
  email: david3@live.unc.edu

## owner/author
owner:
  name: Ben Knoble
  avatar: benknoble.png
  email: david3@live.unc.edu
  phone: +33.(0).7.68.71.98.44
  description: Je d&#233;cris ce que j&#39;ai fait ou regard&#233; &#224; Montpellier !
  github: benknoble
  stackexchange: david-ben-knoble
  linkedin: https://linkedin.com/in/ben-knoble

## sidebar links
links:
  - title: <i class="iconside iconm-home"></i> Accueil
    url: /
  - title: <i class="iconside iconm-user"></i> Info
    url: /about/
  - title: <i class="iconside iconm-quill"></i> Blog
    url: /blog/
  - title: <i class="fa fa-tags"></i> Mots Clés
    url: /tags/
  - title: <i class="fa fa-archive"></i> Archive
    url: /archive/
  - title: <i class="iconside iconm-envelop"></i> Contact
    url: /contact/
  - title: <i class="iconside iconm-feed2"></i> Feed
    url: /feed.xml

# plugins
plugins:
  - jekyll-sitemap

# jekyll serve
destination: _site
include:
  - .htaccess
exclude:
  - serve
  - README.md
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

# github defaults
github: [metadata]
encoding: UTF-8
kramdown:
  input: GFM
  hard_wrap: false
future: true
jailed: false
# theme: jekyll-theme-primer
gfm_quirks: paragraph_end
