#! /usr/bin/env bash

set -euo pipefail
site_source="$( cd "$( dirname "${BASH_SOURCE[0]}")" && pwd )"

message() {
  echo "$@" >&2
}

die() {
  exit 1
}

bad_env() {
  message "Bad JEKYLL_ENV type $1 !"
  die
}

env_type() {
  local env_type
  case "$1" in
    dev*)   env_type="development"  ;;
    prod*)  env_type="production"   ;;
    *)      bad_env "$1"            ;;
  esac
  echo "${env_type}"
}

serve() {
  local env_used
  env_used="$(env_type "$1")"
  message "Using JEKYLL_ENV ${env_used}"
  JEKYLL_ENV="${env_used}" bundle exec jekyll serve --watch
}

env_arg="${1:-development}"
serve "${env_arg}"
